language: node_js
node_js:
- '12'
sudo: false

branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  app: shopping-cart-mf
  api_key:
    secure: b32Nxgd7T+mCmHl8qhvTULO6GO8jMnYB2Y4jxUe9c70IfClxpz/VbiqRX/ZX6pygG1YC09JQmPYcKYVye2CBk2XpqKY7HbUl15IhIco795rFKWta72UWZ2HDsiGof8l1XvL5+HriJSMDAQ1LrscrkIvvByJHTnlDZ8By1YagX2TjkFB71xTUZVq9kPct4OAewFOXtIjahi4eIWn/w7rpWnQyRzElo7yUkLSs7Dz3S1jYbyapEPOhpU5RBehzkCqmeosRLCInbyB9wWQl6Na7CW458wxxEqJJJh3ZwJtC7bHKm8kCrOMdTzqvQp+JLIQIO2LjNpItE+i/QvlBkU4oL7NtAQToMMZlzidX3GItQNGdKPNJpZLa7EhX90oUvCyFvq+hVRso3zlwFrL6/WZVJDpFaV7UWfeUb5biWwGmpBx4/SFX/QHqR9APAx9B4znq6TONQPVwl+5Nnc4YXXqy+PCq1O3dXhupqPGCmHhLv0yhF+qKXh6P+FKyDGLZyTEoLRuiu9z1ejLwtm9n6fkwGBNR75lEjM5u0gz5J+N/3F/eeyGWPbZeTmD5qFjht7+gQOmlleExIDq3tOh4+hQp6xEtqaTBke/CD15hO4M8AnvuhoPmSSiCQwvRkeQlQnuI8SZnOVmXR0bE9UbxLi4Yq0nJlwt/nM0AM0gkNS2xyEs=
